server:
  port: 8080
spring:
  application:
    name: HealthCareEx
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    password: Q_NKphLW.)aUT27@6R+vd
    url: jdbc:sqlserver://10.230.146.74:1433;databaseName=MGCB_AMANDA;encrypt=true;trustServerCertificate=true
    username: AmandaUser
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
